version: '3.8'

services:
  backend:
    build: .
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/App-menu
      - MERCADOPAGO_ACCESS_TOKEN=APP_USR-1267889710077671-062210-45b06e71f851ca42e3094b3f016aeada-2508495279
      - FRONTEND_PUBLIC_URL=https://a31b-179-234-108-186.ngrok-free.app
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
